name: SummerTime

on:
#  push:
#    branches: ['main']
#    paths:
#      - '**/summer.*'
#      - 'sub/*.txt'
#  schedule:
#    - cron: '30 1,9,17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        dummy: ['single']
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
          architecture: x64
          cache: 'pip'
          cache-dependency-path: 'edge/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r edge/requirements.txt || exit 1

      - name: Run script
        run: |
          python edge/summer.py

      - name: Commit and push if changes any
        run: |
          git config --local user.name "google-labs-jules[bot]'"
          git config --local user.email "161369871+google-labs-jules[bot]@users.noreply.github.com"
          git add sub/*.txt

          if ! git diff --quiet || ! git diff --staged --quiet; then
            git commit -m "WireGuard configs harvest at: $(TZ='Asia/Tehran' date '+%H:%M:%S')" \
                       -m "The new wireguard configurations were obtained from Telegram channels, And subsequently added to the list corresponding to their respective clients." \
                       --author="Diana-Cl <135276904+Diana-Cl@users.noreply.github.com>"
            git push || exit 1
          else
            echo "No changes detected. Skipping commit and push."
          fi
